create table person (
	id INT NOT NULL PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	email VARCHAR(50),
	gender VARCHAR(30) NOT NULL,
	contry VARCHAR(50) NOT NULL
);
insert into person (id, first_name, last_name, email, gender, contry) values (1, 'Aymer', 'Gieraths', 'agieraths0@globo.com', 'Male', 'China');
insert into person (id, first_name, last_name, email, gender, contry) values (2, 'Dina', 'Krimmer', 'dkrimmer1@ovh.net', 'Female', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, contry) values (3, 'Hayley', 'Blaise', 'hblaise2@purevolume.com', 'Female', 'Portugal');
insert into person (id, first_name, last_name, email, gender, contry) values (4, 'Nadean', 'Dunbobin', 'ndunbobin3@oakley.com', 'Female', 'United States');
insert into person (id, first_name, last_name, email, gender, contry) values (5, 'Cosetta', 'Taggett', 'ctaggett4@reuters.com', 'Female', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, contry) values (6, 'Odey', 'Barnicott', 'obarnicott5@gizmodo.com', 'Male', 'Afghanistan');
insert into person (id, first_name, last_name, email, gender, contry) values (7, 'Randy', 'McRuvie', 'rmcruvie6@usgs.gov', 'Non-binary', 'Latvia');
insert into person (id, first_name, last_name, email, gender, contry) values (8, 'Lanna', 'Canton', 'lcanton7@slate.com', 'Bigender', 'China');
insert into person (id, first_name, last_name, email, gender, contry) values (9, 'Ludovika', 'Sabati', 'lsabati8@flickr.com', 'Female', 'Germany');
insert into person (id, first_name, last_name, email, gender, contry) values (10, 'Agatha', 'Hiner', 'ahiner9@forbes.com', 'Female', 'Kazakhstan');
insert into person (id, first_name, last_name, email, gender, contry) values (11, 'Bunnie', 'MacVicar', 'bmacvicara@blogger.com', 'Female', 'Japan');
insert into person (id, first_name, last_name, email, gender, contry) values (12, 'Britt', 'Heady', 'bheadyb@nhs.uk', 'Male', 'China');
insert into person (id, first_name, last_name, email, gender, contry) values (13, 'Lena', 'Kilgrove', 'lkilgrovec@aol.com', 'Genderfluid', 'Argentina');
insert into person (id, first_name, last_name, email, gender, contry) values (14, 'Matthieu', 'Lamming', 'mlammingd@youtube.com', 'Male', 'Mozambique');
insert into person (id, first_name, last_name, email, gender, contry) values (15, 'Estevan', 'Mattea', 'ematteae@house.gov', 'Male', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, contry) values (16, 'Carma', 'Kohring', 'ckohringf@booking.com', 'Female', 'Philippines');
insert into person (id, first_name, last_name, email, gender, contry) values (17, 'Blair', 'Kirby', 'bkirbyg@privacy.gov.au', 'Genderqueer', 'Kosovo');
insert into person (id, first_name, last_name, email, gender, contry) values (18, 'Zachery', 'Montford', 'zmontfordh@bing.com', 'Male', 'France');
insert into person (id, first_name, last_name, email, gender, contry) values (19, 'Sybila', 'Meek', 'smeeki@fotki.com', 'Female', 'Ecuador');
insert into person (id, first_name, last_name, email, gender, contry) values (20, 'Anne-corinne', 'Scruby', 'ascrubyj@lycos.com', 'Female', 'Japan');
insert into person (id, first_name, last_name, email, gender, contry) values (21, 'Hasheem', 'Addy', 'haddyk@house.gov', 'Male', 'Dominican Republic');
insert into person (id, first_name, last_name, email, gender, contry) values (22, 'Werner', 'Corteney', 'wcorteneyl@gov.uk', 'Male', 'South Korea');
insert into person (id, first_name, last_name, email, gender, contry) values (23, 'Elvis', 'Cleare', 'eclearem@bandcamp.com', 'Male', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, contry) values (24, 'Errick', 'Woollard', 'ewoollardn@php.net', 'Male', 'China');
insert into person (id, first_name, last_name, email, gender, contry) values (25, 'Conant', 'Denson', 'cdensono@gnu.org', 'Male', 'Poland');
insert into person (id, first_name, last_name, email, gender, contry) values (26, 'Pepita', 'Figgures', 'pfigguresp@163.com', 'Female', 'Yemen');
insert into person (id, first_name, last_name, email, gender, contry) values (27, 'Doe', 'Di Antonio', 'ddiantonioq@cbslocal.com', 'Polygender', 'Kazakhstan');
insert into person (id, first_name, last_name, email, gender, contry) values (28, 'Johanna', 'Ondrus', 'jondrusr@msn.com', 'Agender', 'Syria');
insert into person (id, first_name, last_name, email, gender, contry) values (29, 'Prue', 'Edgerly', 'pedgerlys@china.com.cn', 'Female', 'China');
insert into person (id, first_name, last_name, email, gender, contry) values (30, 'Cathie', 'Koppens', 'ckoppenst@nymag.com', 'Female', 'Madagascar');
insert into person (id, first_name, last_name, email, gender, contry) values (31, 'Torrance', 'Choat', 'tchoatu@spiegel.de', 'Male', 'Croatia');
insert into person (id, first_name, last_name, email, gender, contry) values (32, 'Ronny', 'Dumini', 'rduminiv@ehow.com', 'Female', 'Czech Republic');
insert into person (id, first_name, last_name, email, gender, contry) values (33, 'Suzanna', 'Dolbey', 'sdolbeyw@wordpress.org', 'Female', 'Philippines');
insert into person (id, first_name, last_name, email, gender, contry) values (34, 'Neils', 'Iskower', 'niskowerx@paginegialle.it', 'Male', 'China');
insert into person (id, first_name, last_name, email, gender, contry) values (35, 'Munroe', 'Bausor', 'mbausory@theatlantic.com', 'Male', 'Guatemala');
insert into person (id, first_name, last_name, email, gender, contry) values (36, 'Marjorie', 'Leggitt', 'mleggittz@house.gov', 'Female', 'Albania');
insert into person (id, first_name, last_name, email, gender, contry) values (37, 'Mickey', 'Thonger', 'mthonger10@w3.org', 'Male', 'United States');
insert into person (id, first_name, last_name, email, gender, contry) values (38, 'Adler', 'Jimmes', 'ajimmes11@opensource.org', 'Male', 'Canada');
insert into person (id, first_name, last_name, email, gender, contry) values (39, 'Kele', 'Almon', 'kalmon12@acquirethisname.com', 'Male', 'Yemen');
insert into person (id, first_name, last_name, email, gender, contry) values (40, 'Giraud', 'Alleyne', 'galleyne13@nature.com', 'Male', 'China');
insert into person (id, first_name, last_name, email, gender, contry) values (41, 'Archy', 'O''Regan', 'aoregan14@auda.org.au', 'Male', 'Czech Republic');
insert into person (id, first_name, last_name, email, gender, contry) values (42, 'Constantin', 'Zima', 'czima15@ox.ac.uk', 'Male', 'Croatia');
insert into person (id, first_name, last_name, email, gender, contry) values (43, 'Georgena', 'Piotr', 'gpiotr16@wired.com', 'Female', 'Afghanistan');
insert into person (id, first_name, last_name, email, gender, contry) values (44, 'Mavis', 'Garber', 'mgarber17@digg.com', 'Female', 'Panama');
insert into person (id, first_name, last_name, email, gender, contry) values (45, 'Tully', 'd''Arcy', 'tdarcy18@whitehouse.gov', 'Male', 'France');
insert into person (id, first_name, last_name, email, gender, contry) values (46, 'Phylis', 'Hartwell', 'phartwell19@joomla.org', 'Genderfluid', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, contry) values (47, 'Justino', 'Willcott', 'jwillcott1a@usatoday.com', 'Bigender', 'China');
insert into person (id, first_name, last_name, email, gender, contry) values (48, 'Ulrika', 'Bovaird', 'ubovaird1b@archive.org', 'Female', 'Philippines');
insert into person (id, first_name, last_name, email, gender, contry) values (49, 'Tamiko', 'Humphrys', 'thumphrys1c@state.tx.us', 'Agender', 'Zambia');
insert into person (id, first_name, last_name, email, gender, contry) values (50, 'Jillana', 'Shewery', 'jshewery1d@csmonitor.com', 'Non-binary', 'Thailand');
insert into person (id, first_name, last_name, email, gender, contry) values (51, 'Lianne', 'Fildes', 'lfildes1e@theguardian.com', 'Female', 'Thailand');
insert into person (id, first_name, last_name, email, gender, contry) values (52, 'Nathanael', 'Sketchley', 'nsketchley1f@com.com', 'Male', 'Mexico');
insert into person (id, first_name, last_name, email, gender, contry) values (53, 'Josephine', 'Sacase', 'jsacase1g@java.com', 'Female', 'Russia');
insert into person (id, first_name, last_name, email, gender, contry) values (54, 'Arni', 'Dominick', 'adominick1h@ed.gov', 'Male', 'Thailand');
insert into person (id, first_name, last_name, email, gender, contry) values (55, 'Gus', 'Sutcliffe', 'gsutcliffe1i@gnu.org', 'Male', 'Czech Republic');
insert into person (id, first_name, last_name, email, gender, contry) values (56, 'Gustie', 'Burdoun', 'gburdoun1j@diigo.com', 'Female', 'Mauritania');
insert into person (id, first_name, last_name, email, gender, contry) values (57, 'Charline', 'Slowly', 'cslowly1k@ask.com', 'Female', 'Brazil');
insert into person (id, first_name, last_name, email, gender, contry) values (58, 'Omero', 'Chatainier', 'ochatainier1l@chicagotribune.com', 'Male', 'Iran');
insert into person (id, first_name, last_name, email, gender, contry) values (59, 'Justus', 'Pessler', 'jpessler1m@soup.io', 'Male', 'China');
insert into person (id, first_name, last_name, email, gender, contry) values (60, 'Cornell', 'Cherry', 'ccherry1n@blog.com', 'Genderfluid', 'Poland');
insert into person (id, first_name, last_name, email, gender, contry) values (61, 'Grace', 'Pillington', 'gpillington1o@wordpress.com', 'Polygender', 'Russia');
insert into person (id, first_name, last_name, email, gender, contry) values (62, 'Fernande', 'Ferriday', 'fferriday1p@seesaa.net', 'Female', 'Montenegro');
insert into person (id, first_name, last_name, email, gender, contry) values (63, 'Kendra', 'Bilbrook', 'kbilbrook1q@google.co.jp', 'Female', 'French Guiana');
insert into person (id, first_name, last_name, email, gender, contry) values (64, 'Korey', 'Tainton', 'ktainton1r@friendfeed.com', 'Male', 'Bulgaria');
insert into person (id, first_name, last_name, email, gender, contry) values (65, 'Garik', 'Tomaello', 'gtomaello1s@livejournal.com', 'Non-binary', 'Czech Republic');
insert into person (id, first_name, last_name, email, gender, contry) values (66, 'Tomaso', 'Espinet', 'tespinet1t@cbsnews.com', 'Male', 'Yemen');
insert into person (id, first_name, last_name, email, gender, contry) values (67, 'Timmy', 'Pettyfer', 'tpettyfer1u@fastcompany.com', 'Genderfluid', 'Philippines');
insert into person (id, first_name, last_name, email, gender, contry) values (68, 'Cathryn', 'Izhak', 'cizhak1v@amazon.de', 'Female', 'Canada');
insert into person (id, first_name, last_name, email, gender, contry) values (69, 'Pierson', 'De Ambrosis', 'pdeambrosis1w@addtoany.com', 'Male', 'Bangladesh');
insert into person (id, first_name, last_name, email, gender, contry) values (70, 'Riannon', 'Chasmoor', 'rchasmoor1x@cdc.gov', 'Female', 'Russia');
insert into person (id, first_name, last_name, email, gender, contry) values (71, 'De', 'Howton', 'dhowton1y@statcounter.com', 'Female', 'France');
insert into person (id, first_name, last_name, email, gender, contry) values (72, 'Waldo', 'Gibben', 'wgibben1z@zdnet.com', 'Male', 'China');
insert into person (id, first_name, last_name, email, gender, contry) values (73, 'Jacinda', 'Northcote', 'jnorthcote20@wunderground.com', 'Female', 'Mauritius');
insert into person (id, first_name, last_name, email, gender, contry) values (74, 'Stacia', 'Ellams', 'sellams21@over-blog.com', 'Female', 'Russia');
insert into person (id, first_name, last_name, email, gender, contry) values (75, 'Haze', 'Farrar', 'hfarrar22@java.com', 'Male', 'Bulgaria');
insert into person (id, first_name, last_name, email, gender, contry) values (76, 'Jolynn', 'Dooly', 'jdooly23@redcross.org', 'Female', 'Ukraine');
insert into person (id, first_name, last_name, email, gender, contry) values (77, 'Sauveur', 'Marrable', 'smarrable24@fastcompany.com', 'Male', 'Portugal');
insert into person (id, first_name, last_name, email, gender, contry) values (78, 'Evan', 'Burchess', 'eburchess25@bluehost.com', 'Male', 'Kenya');
insert into person (id, first_name, last_name, email, gender, contry) values (79, 'Marga', 'Gorgl', 'mgorgl26@adobe.com', 'Female', 'Portugal');
insert into person (id, first_name, last_name, email, gender, contry) values (80, 'Ruperto', 'Faireclough', 'rfaireclough27@mit.edu', 'Male', 'Uzbekistan');
insert into person (id, first_name, last_name, email, gender, contry) values (81, 'Deloris', 'Nehls', 'dnehls28@si.edu', 'Bigender', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, contry) values (82, 'Mathilde', 'Cappleman', 'mcappleman29@economist.com', 'Female', 'China');
insert into person (id, first_name, last_name, email, gender, contry) values (83, 'Marten', 'Sallowaye', 'msallowaye2a@blogtalkradio.com', 'Male', 'France');
insert into person (id, first_name, last_name, email, gender, contry) values (84, 'Corette', 'Itzhaiek', 'citzhaiek2b@so-net.ne.jp', 'Female', 'China');
insert into person (id, first_name, last_name, email, gender, contry) values (85, 'Tiphani', 'Petr', 'tpetr2c@goodreads.com', 'Female', 'Japan');
insert into person (id, first_name, last_name, email, gender, contry) values (86, 'Howey', 'Buxcy', 'hbuxcy2d@princeton.edu', 'Male', 'Colombia');
insert into person (id, first_name, last_name, email, gender, contry) values (87, 'Leonelle', 'Aleswell', 'laleswell2e@redcross.org', 'Agender', 'Japan');
insert into person (id, first_name, last_name, email, gender, contry) values (88, 'Margret', 'Vargas', 'mvargas2f@state.tx.us', 'Female', 'Mexico');
insert into person (id, first_name, last_name, email, gender, contry) values (89, 'Harlie', 'Spillman', 'hspillman2g@yahoo.co.jp', 'Female', 'Tanzania');
insert into person (id, first_name, last_name, email, gender, contry) values (90, 'Christie', 'Harg', 'charg2h@oaic.gov.au', 'Male', 'Namibia');
insert into person (id, first_name, last_name, email, gender, contry) values (91, 'Solly', 'Abilowitz', 'sabilowitz2i@myspace.com', 'Male', 'Indonesia');
insert into person (id, first_name, last_name, email, gender, contry) values (92, 'Adamo', 'Easterling', 'aeasterling2j@jimdo.com', 'Genderqueer', 'China');
